 name: Sync WeRead to Notion

on:
  schedule:
    - cron: "0 12 * * *"  # 北京时间20:00运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run synchronization
        env:
          WR_TOKEN: ${{ secrets.WR_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python main.py
        
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: sync-logs
          path: logs/
